config/routes.rb
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    get "dashboard" => "dashboard#index"
    get "dashboard/general" => "dashboard#general"
    get "dashboard/moderation" => "dashboard#moderation"
    get "dashboard/security" => "dashboard#security"
    get "dashboard/reports" => "dashboard#reports"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        resources :keys, controller: 'api', only: [:index, :show, :update, :create, :destroy] do
          member do
            post "revoke" => "api#revoke_key"
            post "undo-revoke" => "api#undo_revoke_key"
          end
        end

        resources :web_hooks
        get 'web_hook_events/:id' => 'web_hooks#list_events', as: :web_hook_events
        get 'web_hooks/:id/events' => 'web_hooks#list_events'
        get 'web_hooks/:id/events/bulk' => 'web_hooks#bulk_events'
        post 'web_hooks/:web_hook_id/events/:event_id/redeliver' => 'web_hooks#redeliver_event'
        post 'web_hooks/:id/ping' => 'web_hooks#ping'
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: RouteFormat.backup }
        put "" => "backups#email", constraints: { id: RouteFormat.backup }
        delete "" => "backups#destroy", constraints: { id: RouteFormat.backup }
        post "restore" => "backups#restore", constraints: { id: RouteFormat.backup }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        delete "cancel" => "backups#cancel"
        post "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_backup_chunk"
        post "upload" => "backups#upload_backup_chunk"
        get "upload_url" => "backups#create_upload_url"
      end
    end

    resources :badges, constraints: AdminConstraint.new do
      collection do
        get "types" => "badges#badge_types"
        post "badge_groupings" => "badges#save_badge_groupings"
        post "preview" => "badges#preview"
      end
    end

  end # admin namespace

  get "email_preferences" => "email#preferences_redirect", :as => "email_preferences_redirect"

  get "email/unsubscribe/:key" => "email#unsubscribe", as: "email_unsubscribe"
  get "email/unsubscribed" => "email#unsubscribed", as: "email_unsubscribed"
  post "email/unsubscribe/:key" => "email#perform_unsubscribe", as: "email_perform_unsubscribe"

  get "extra-locales/:bundle" => "extra_locales#show"

  resources :session, id: RouteFormat.username, only: [:create, :destroy, :become] do
    if !Rails.env.production?
      get 'become'
    end

    collection do
      post "forgot_password"
    end
  end

  get "review" => "reviewables#index" # For ember app
  get "review/:reviewable_id" => "reviewables#show", constraints: { reviewable_id: /\d+/ }
  get "review/:reviewable_id/explain" => "reviewables#explain", constraints: { reviewable_id: /\d+/ }
  get "review/topics" => "reviewables#topics"
  get "review/settings" => "reviewables#settings"
  put "review/settings" => "reviewables#settings"
  put "review/:reviewable_id/perform/:action_id" => "reviewables#perform", constraints: {
    reviewable_id: /\d+/,
    action_id: /[a-z\_]+/
  }
  put "review/:reviewable_id" => "reviewables#update", constraints: { reviewable_id: /\d+/ }
  delete "review/:reviewable_id" => "reviewables#destroy", constraints: { reviewable_id: /\d+/ }

  resources :reviewable_claimed_topics

  get "session/sso" => "session#sso"
  get "session/sso_login" => "session#sso_login"
  get "session/sso_provider" => "session#sso_provider"
  get "session/current" => "session#current"
  get "session/csrf" => "session#csrf"
  get "session/email-login/:token" => "session#email_login_info"
  post "session/email-login/:token" => "session#email_login"
  get "session/otp/:token" => "session#one_time_password", constraints: { token: /[0-9a-f]+/ }
  post "session/otp/:token" => "session#one_time_password", constraints: { token: /[0-9a-f]+/ }
  get "composer_messages" => "composer_messages#index"
  post "composer/parse_html" => "composer#parse_html"

  resources :static
  post "login" => "static#enter"
  get "login" => "static#show", id: "login"
  get "password-reset" => "static#show", id: "password_reset"
  get "faq" => "static#show", id: "faq"
  get "tos" => "static#show", id: "tos", as: 'tos'
  get "privacy" => "static#show", id: "privacy", as: 'privacy'
  get "signup" => "static#show", id: "signup"
  get "login-preferences" => "static#show", id: "login"

  %w{guidelines rules conduct}.each do |faq_alias|
    get faq_alias => "static#show", id: "guidelines", as: faq_alias
  end

  get "my/*path", to: 'users#my_redirect'
  get "user_preferences" => "users#user_preferences_redirect"
  get ".well-known/change-password", to: redirect(relative_url_root + 'my/preferences/account', status: 302)

  %w{users u}.each_with_index do |root_path, index|
    get "#{root_path}" => "users#index", constraints: { format: 'html' }

    resources :users, except: [:index, :new, :show, :update, :destroy], path: root_path do
      collection do
        get "check_username"
        get "is_local_username"
      end
    end

    post "#{root_path}/second_factors" => "users#list_second_factors"
    put "#{root_path}/second_factor" => "users#update_second_factor"

    post "#{root_path}/create_second_factor_security_key" => "users#create_second_factor_security_key"
    post "#{root_path}/register_second_factor_security_key" => "users#register_second_factor_security_key"
    put "#{root_path}/security_key" => "users#update_security_key"
    post "#{root_path}/create_second_factor_totp" => "users#create_second_factor_totp"
    post "#{root_path}/enable_second_factor_totp" => "users#enable_second_factor_totp"
    put "#{root_path}/disable_second_factor" => "users#disable_second_factor"

    put "#{root_path}/second_factors_backup" => "users#create_second_factor_backup"

    put "#{root_path}/update-activation-email" => "users#update_activation_email"
    get "#{root_path}/hp" => "users#get_honeypot_value"
    post "#{root_path}/email-login" => "users#email_login"
    get "#{root_path}/admin-login" => "users#admin_login"
    put "#{root_path}/admin-login" => "users#admin_login"
    get "#{root_path}/admin-login/:token" => "users#admin_login"
    put "#{root_path}/admin-login/:token" => "users#admin_login"
    post "#{root_path}/toggle-anon" => "users#toggle_anon"
    post "#{root_path}/read-faq" => "users#read_faq"
    get "#{root_path}/search/users" => "users#search_users"

    get({ "#{root_path}/account-created/" => "users#account_created" }.merge(index == 1 ? { as: :users_account_created } : { as: :old_account_created }))

    get "#{root_path}/account-created/resent" => "users#account_created"
    get "#{root_path}/account-created/edit-email" => "users#account_created"
    get({ "#{root_path}/password-reset/:token" => "users#password_reset" }.merge(index == 1 ? { as: :password_reset_token } : {}))
    get "#{root_path}/confirm-email-token/:token" => "users#confirm_email_token", constraints: { format: 'json' }
    put "#{root_path}/password-reset/:token" => "users#password_reset"
    get "#{root_path}/activate-account/:token" => "users#activate_account"
    put({ "#{root_path}/activate-account/:token" => "users#perform_account_activation" }.merge(index == 1 ? { as: 'perform_activate_account' } : {}))

    get "#{root_path}/confirm-old-email/:token" => "users_email#show_confirm_old_email"
    put "#{root_path}/confirm-old-email" => "users_email#confirm_old_email"

    get "#{root_path}/confirm-new-email/:token" => "users_email#show_confirm_new_email"
    put "#{root_path}/confirm-new-email" => "users_email#confirm_new_email"

    get({
      "#{root_path}/confirm-admin/:token" => "users#confirm_admin",
      constraints: { token: /[0-9a-f]+/ }
    }.merge(index == 1 ? { as: 'confirm_admin' } : {}))
    post "#{root_path}/confirm-admin/:token" => "users#confirm_admin", constraints: { token: /[0-9a-f]+/ }
    get "#{root_path}/:username/private-messages" => "user_actions#private_messages", constraints: { username: RouteFormat.username }
    get "#{root_path}/:username/private-messages/:filter" => "user_actions#private_messages", constraints: { username: RouteFormat.username }
    get "#{root_path}/:username/messages" => "user_actions#private_messages", constraints: { username: RouteFormat.username }
    get "#{root_path}/:username/messages/:filter" => "user_actions#private_messages", constraints: { username: RouteFormat.username }
    get "#{root_path}/:username/messages/group/:group_name" => "user_actions#private_messages", constraints: { username: RouteFormat.username, group_name: RouteFormat.username }
    get "#{root_path}/:username/messages/group/:group_name/archive" => "user_actions#private_messages", constraints: { username: RouteFormat.username, group_name: RouteFormat.username }
    get "#{root_path}/:username/messages/tags/:tag_id" => "user_actions#private_messages", constraints: StaffConstraint.new
    get "#{root_path}/:username.json" => "users#show", constraints: { username: RouteFormat.username }, defaults: { format: :json }
    get({ "#{root_path}/:username" => "users#show", constraints: { username: RouteFormat.username } }.merge(index == 1 ? { as: 'user' } : {}))
    put "#{root_path}/:username" => "users#update", constraints: { username: RouteFormat.username }, defaults: { format: :json }
    get "#{root_path}/:username/emails" => "users#check_emails", constraints: { username: RouteFormat.username }

app/models/reports/topics.rb
# frozen_string_literal: true

Report.add_report('topics') do |report|
  category_filter = report.filters.dig(:category)
  report.add_filter('category', default: category_filter)

  basic_report_about report, Topic, :listable_count_per_day, report.start_date, report.end_date, category_filter

  countable = Topic.listable_topics
  if category_filter
    countable = countable.in_category_and_subcategories(category_filter)
  end
  add_counts report, countable, 'topics.created_at'
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

module TopicsHelper
  include ApplicationHelper

  def render_topic_title(topic)
    link_to(Emoji.gsub_emoji_to_unicode(topic.title), topic.relative_url)
  end

  def categories_breadcrumb(topic)
    breadcrumb = []

    category = topic.category
    if category && !category.uncategorized?
      if (parent = category.parent_category)
        breadcrumb.push url: parent.url, name: parent.name
      end
      breadcrumb.push url: category.url, name: category.name
    end

    Plugin::Filter.apply(:topic_categories_breadcrumb, topic, breadcrumb)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%= html_lang %>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, published_time: @topic_view.published_time) %>
  <% if @topic_view.prev_page %>
    <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
  <% end %>
  <% if @topic_view.next_page %>
    <link rel="next" href="<%= @topic_view.next_page_path -%>">
  <% end %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username %></b> <%= "(#{post.user.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names?) %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<% if @topic_view %>
  <h1 class="crawler-topic-title">
    <%= render_topic_title(@topic_view.topic) %>
  </h1>

  <% @breadcrumbs = categories_breadcrumb(@topic_view.topic)
      if @breadcrumbs.present? %>
  <div id='breadcrumbs'>
    <% @breadcrumbs.each_with_index do |c,i| %>
      <div id="breadcrumb-<%=i%>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
        <%-if (i+1) < @breadcrumbs.length%>
          itemref="breadcrumb-<%=(i+1)%>"
        <%-end%>>
        <a href="<%=c[:url]%>" itemprop="url" class='badge-wrapper bullet'>
          <span class="badge-category-bg"></span>
          <span itemprop="title" class='category-title'><%=c[:name]%></span>
        </a>
      </div>
    <% end %>
  </div>
  <% end %>

  <% if SiteSetting.tagging_enabled %>
    <% @tags = @topic_view.topic.tags %>
    <% if @tags.present? %>
      <div class='crawler-tags-list' itemscope itemtype='http://schema.org/DiscussionForumPosting'>
        <% @tags.each_with_index do |tag, i| %>
          <div itemprop='keywords'>
            <a  href='<%= "#{Discourse.base_url}/tags/#{tag.name}" %>' rel="tag">
              <span itemprop='headline'><%= tag.name -%></span>
            </a>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <%= server_plugin_outlet "topic_header" %>

  <%- if include_crawler_content? %>

  <% @topic_view.posts.each do |post| %>
    <div itemscope itemtype='http://schema.org/DiscussionForumPosting' class='topic-body crawler-post'>
      <% if (u = post.user) %>
        <div class='crawler-post-meta'>
          <span class="creator" itemprop="author" itemscope itemtype="http://schema.org/Person">
            <a itemprop="url" href='<%= Discourse.base_uri %>/u/<%= u.username %>'><span itemprop='name'><%= u.username %></span></a>
            <%= "(#{u.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names? && !u.name.blank?) %>
            <%
              post_custom_fields = @topic_view.post_custom_fields[post.id] || {}
              who_username = post_custom_fields["action_code_who"] || ""
              if post.action_code
            %>
              <%= t("js.action_codes.#{post.action_code}", when: "", who: who_username).html_safe %>
            <% end %>
          </span>

          <span class="crawler-post-infos">
            <% if post.updated_at > post.created_at %>
              <meta itemprop='datePublished' content='<%= post.created_at.to_formatted_s(:iso8601) %>'>
              <time itemprop='dateModified' datetime='<%= post.updated_at.to_formatted_s(:iso8601) %>' class='post-time'>
                <%= l post.updated_at, format: :long %>
              </time>
            <% else %>
              <time itemprop='datePublished' datetime='<%= post.created_at.to_formatted_s(:iso8601) %>' class='post-time'>
                <%= l post.created_at, format: :long %>
              </time>
            <% end %>
          <span itemprop='position'>#<%= post.post_number %></span>
          </span>
        </div>
        <div class='post' itemprop='articleBody'>
          <%= post.hidden ? t('flagging.user_must_edit').html_safe : post.cooked.html_safe %>
        </div>

        <meta itemprop='headline' content='<%= @topic_view.title %>'>

        <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
           <meta itemprop="interactionType" content="http://schema.org/LikeAction"/>
           <meta itemprop="userInteractionCount" content="<%= post.like_count %>" />
           <span class='post-likes'><%= post.like_count > 0 ? t('post.has_likes', count: post.like_count) : '' %></span>
         </div>

         <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
            <meta itemprop="interactionType" content="http://schema.org/CommentAction"/>
            <meta itemprop="userInteractionCount" content="<%= post.reply_count %>" />
          </div>

          <% if @topic_view.link_counts[post.id] && @topic_view.link_counts[post.id].length > 0 %>
            <div class='crawler-linkback-list' itemscope itemtype='http://schema.org/ItemList'>
              <% @topic_view.link_counts[post.id].each_with_index do |link, i| %>
                <% if link[:reflection] && link[:title].present? %>
                  <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
                    <a href="<%=link[:url]%>" itemprop='item'>
                      <meta itemprop='url' content='<%=link[:url]%>'>
                      <meta itemprop='position' content='<%= i+1 %>'>
                      <span itemprop='name'><%=link[:title]%></span>
                    </a>
                  </div>
                <% end %>
              <% end %>
            </div>
         <% end %>

      <% end %>
    </div>
  <% end %>

  <% if @topic_view.prev_page || @topic_view.next_page %>
    <div role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement' class="topic-body crawler-post">
      <% if @topic_view.prev_page %>
        <span itemprop='name'><%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev', itemprop: 'url' %></span>
      <% end %>
      <% if @topic_view.next_page %>
        <span itemprop='name'><b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next', itemprop: 'url' %></b></span>
      <% end %>
    </div>
  <% end %>

  <% end %>

  <% content_for :head do %>
    <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
    <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, ignore_canonical: true, published_time: @topic_view.published_time) %>

    <% if @topic_view.prev_page || @topic_view.next_page %>
      <% if @topic_view.prev_page %>
        <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
      <% end %>
      <% if @topic_view.next_page %>
        <link rel="next" href="<%= @topic_view.next_page_path -%>">
      <% end %>
    <% end %>
  <% end %>

  <% content_for(:title) { @title || "#{gsub_emoji_to_unicode(@topic_view.page_title)} - #{SiteSetting.title}" } %>

  <% if @topic_view.print %>
    <% content_for :after_body do %>
        <%= preload_script('print-page') %>
    <% end %>
  <% end %>
<% end %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% topic_url = @topic_view.absolute_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <% if lang %><language><%= lang.sub('_', '-')%></language><% end %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <dc:creator><![CDATA[<%= "@#{post.user.username}#{" #{post.user.name}" if (post.user.name.present? && SiteSetting.enable_names?)}" -%>]]></dc:creator>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <p><%= t('author_wrote', author: link_to("@#{post.user.username}", "#{Discourse.base_url}/u/#{url_encode(post.user.username_lower)}")).html_safe %></p>
          <blockquote>
            <% if post.hidden %>
              <%= t('flagging.user_must_edit').html_safe %>
            <% else %>
              <%= post.cooked.html_safe %>
            <% end %>
          </blockquote>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false"><%= Discourse.current_hostname %>-post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= topic_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>